---
title: "Project name"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup


This repository contains two main pieces of code:

* the `/silRnetz` package
* the shiny app interface in `/shinyapp`
and the setup follows this order:

0. Install R and RStudio
1. Download/clone the repository
2. Obtain the `api_spec.R` file and place this file under `/R`. The valid keys can be
obtained from Inopla and the final file should look like this:
```
url_base <- "url"
api_urls <- list()
api_urls[['Dest']] <-  paste(url_base, "hash1/Statistics/EVN/Destinations", sep = '')
api_urls[['Dest_Count']] <- paste(url_base, "hash2/Statistics/EVN/Destinations/COUNT", sep = '')
api_urls[['Numbers']] <- paste(url_base, "hash3/Statistics/EVN/Numbers", sep = '')
api_urls[['Numbers_Count']] <- paste(url_base, "hash4/Statistics/EVN/Numbers/COUNT", sep = '')
api_urls[['Callerlists']] <- paste(url_base, "hash5/Lists/Callerlists/1870/Items", sep = '')
```
3. Install the `silRnetz` package
4. Install Font Open Sans
5. Setting up the data can be done in two ways: The first possibility is just
to copy an existing file called `current_data.csv` from an old installation into
`data/raw`. The second option is to call the `create_current_data` file from the package
manually and give it the corresponding path where to write the `current_data.csv` file.
6. Start the app which allows to update all numbers.
7. Write a bash file that allows to start the app without having to start RStudio
looking something like this with the appropriate paths:
```
"C:/Program Files/R/R-3.6.3/bin/Rscript.exe" -e "shiny::runApp('C:/Users/USER/Desktop/cards', launch.browser = TRUE)"
```


### Data
All the data is obtained from the API using the authentication provided by
the `api_spec.R`. It then gets processed to a level that preserves the anonymitiy
of all callers to an appropriate level and gets stored locally under `/data/raw`.

### Packages and Starting the app

Packages are very outdated but a (hopefully working) state has been collected in an renv environment. 

To install: 

```
install(renv)
renv::restore()
```

Starting the app, you can either use the RStudio interface in `shinyapp/app.R
Starting the app, you can either use the RStudio interface in `shinyapp/app.R` or in the console: 

```
shiny::runApp("shinyapp/app.R")
```

---
### Known issues:
#### OneDrive on Windows-Machines
We encountered the problem that if the default user directory is completely set
up with OneDrive so that all files get synchronized, R can run into problems when
installing new packages and we weren't able to install the silbRnetz package.
The best way to work around this, was to make sure that R is installed in a
directory not linked to OneDrive

#### Fonts on Mac
The map-drawing function with the corresponding fonts still causes trouble on Mac.


